version: "3.8"
services:
  backend:
    build: ./BackEnd
    ports:
      - "4000:4000"
    volumes:
      - ./BackEnd:/backend
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db-data:
