version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
      - /backend/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
